pace-neutrons/Horace

_test/test_sqw/test_fake_sqw.m, algorithms/build_det_from_q_range.m, algorithms/fake_sqw.m, algorithms/private/gen_sqw_check_files.m, algorithms/private/range_add_border.m, sqw/@rundatah/private/calc_sqw_.m
This modifies fake_sqw to accept range of hkl values instead of detector positions to be able to compare the generated sqw object with the results of theoretical simulations. 
The validity of the operations are illustrated by unit test provided. If one generates sqw object using detectors and then deploy q-range as input to another fake sqw, the fake_sqw correctly recovers the detectors positions and produce the result, similar to the one, generated by initial fake_sqw
=> fake sqw with q range

sqw/file_io/@combine_sqw_pix_job/combine_sqw_pix_job.m
This very minor error-message bug will probably never be seen by anyone who is not also (incorrectly) modifying temporary SQW objects which they then write to disk before combining.
=> Fix typo in combine_sqw_pix_job.m error message

documentation/adr/0001-record-architecture-decisions.md, documentation/adr/0002-use-github-for-documentation.md, documentation/adr/0003-use-cmake-for-build.md
The `documentation/adr` folder will be linked from the pace-developers.wiki once this is merged.
See ADR-0002 below for discussion around split between documentation on the wiki and in the Horace project source.
=> Initial ADRs for PACE work on Horace

documentation/adr/0001-record-architecture-decisions.md, documentation/adr/0002-use-github-for-documentation.md, documentation/adr/0003-use-cmake-for-build.md, documentation/adr/0004-cpp-tests-in-separate-projects.md
Create ADR document decisions about C++ test file layout
@hsautessella can you verify the CMake `target_link_libraries` directive is sufficient
Related to #32
=> ADR for CPP test file layout

horace_core/horace_init.m
https://github.com/pace-neutrons/Herbert/pull/88 removes the `copy_git_hooks` function from Herbert. This PR removes all references to it from Horace.
=> Remove call to copy_git_hooks from horace_init

tools/build_config/Jenkinsfile
Previously we were using the "failure" stage to post unsuccessful build, statuses to GitHub, however this block is not entered if the build is manually aborted. This meant that aborted jobs were stuck with the "build running" status on GitHub.
The `unsuccessful` block is entered if the build has any status other than `success` (including `aborted`).
Fixes #150
=> Use Jenkins `unsuccessful` block to post failure statuses

_LowLevelCode/cpp/test/combine_sqw.tests/combine_sqw.test.cpp, _LowLevelCode/cpp/test/combine_sqw.tests/pix_map_tester.h, _test/disabled_tests.md
The disabled tests were failing as they were attempting to read floats from a file, but were reading in 8 bytes, not 4.
I've replaced `ASSERT_EQ` with `EXPECT_EQ` in the tests. As many tests have multiple assertions, this prevents the tests terminating before the rest of the test is run.
There's probably more refactoring/breaking down of tests that can be done, but hopefully this is a start.
=> Refactor and fix combine_sqw C++ unit tests

_test/CMakeLists.txt
The test was timing out regularly (and at different stages) on the Windows build server.
I've also reduced the timeout length for the other tests, since the previous (20 mins) was a bit long. 
Reasoning for 16min timeout on other tests: `test_tobyfit` is the next longest test and takes ~730 seconds on Windows. If other jobs are running this could easily take another couple of minutes and there's also another TobyFit test to re-enable.
Fixes #180
=> Increase CTest timeout for test_sqw to 25 mins

_test/test_sqw_file/test_faccess_sqw_v3.m, horace_core/sqw/file_io/@dnd_binfile_common/dnd_binfile_common.m, horace_core/sqw/file_io/@dnd_file_interface/dnd_file_interface.m
This PR fixes issue, mentioned in Toby's letter from 09/04/2020
test_Toby
*** Writing to C:\Users\tgp98\AppData\Local\Temp\tobyfit_refine_crystal_res.sqw...
Check lattice parameters before application of correction
reference dataset: 5  5  5
Copy of reference dataset before correction applied: 5  5  5
-----------------------------------------------------------------------
Get reorientation matrix to apply to copy of reference dataset only:
-----------------------------------------------------------------------
Check lattice parameters after application of correction
reference dataset: 5  5  5
Copy of reference dataset after correction applied: 4.7468       4.747       4.747
>> 
Latest copy, doing the wrong thing:
>> test_Toby
*** Writing to …
=> wrong faccess initialization

admin/horace_mex.m, documentation/add/01_add.md, documentation/smg/08_setting_up_jenkins_ci.md, documentation/smg/09_version_compatibility.md
This PR removes references to Fortran in Horace docs and build scripts now that the Fortran has been removed from Herbert
Fixes #206
=> Remove references to Fortran in docs and code

documentation/smg/08_setting_up_jenkins_ci.md
Added a section the Jenkins SMG explaining how each pipeline type will deal with Horace's Herbert dependency now that #210 has been merged
=> Update Jenkins SMG with Herbert dependency plan

horace_core/horace_off.m
the issue is related to Herbert [#157](https://github.com/pace-neutrons/Herbert/issues/157)
modified horace_off not to remove horace_on from the path. 
I think its the simplest solution possible.
=> modified horace_off not to remove horace_on

documentation/adr/0012-use-network-storage-for-large-datafiles.md, documentation/adr/0013-use-jenkins-for-secrets-management.md, documentation/adr/0014-use-jenkins-for-network-path-storage.md
Add missing ADRs for the decisions made regarding use of Jenkins for the SAN credentials storage
=> Add ADR for SAN path and credentials management

documentation/smg/09_version_compatibility.md
Minor documentation update to match version added to source tree as part of #142 
Fixes #259
=> Update documented MPICH2 version for Linux

tools/build_config/build.ps1, tools/build_config/build.sh
This adds `-h|-help` and `-h|--help` flags to the `build.ps1` and `build.sh` scripts respectively.
refs: https://github.com/pace-neutrons/Herbert/pull/180
Fixes #257
=> Add help to build scripts

_test/test_sqw/FakeFAccess.m, _test/test_sqw/test_PixelData.m, horace_core/sqw/@PixelData/PixelData.m
This PR ensures that `PixelData.num_pixels` always returns a double. See the corresponding issue (#272) for bug description and reasoning behind the decision.
Fixes #272
=> Always return PixelData.num_pixels as double

_test/test_sqw/FakeFAccess.m, _test/test_sqw/test_PixelData.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelTmpFileHandler/PixelTmpFileHandler.m
This PR implements a non-default `copy` method on `PixelData` that copies temporary files used to save edits to pages of data. This ensures `PixelData` copies are entirely independent of one another.
This PR does _not_ implement a similar thing for copies of `.sqw` files. Creating a copy of an `sqw` object will copy the `PixelData` instance as described above, however the two `PixelData` instances will both still point at the same `.sqw` file; changes to the `.sqw` file will affect both `PixelData` instances. This is a more complicated issue than the one this PR solves. 
Fixes #277
=> Handle copying PixelData instances with tmp files

_test/test_sqw/test_PixelData.m, _test/test_tobyfit/seed_rng.m, _test/test_tobyfit/test_let/test_tobyfit_let_1.m
When setting the seed for a `test_PixelData` and `test_tobyfit_let`, make sure the RNG is set to use the `twister` algorithm. This ensures we get the values we expect.
Fixes #282
=> Ensure tests seeded with mersenne twister

CMakeLists.txt, _LowLevelCode/cpp/accumulate_cut_c/CMakeLists.txt, _LowLevelCode/cpp/bin_pixels_c/CMakeLists.txt, _LowLevelCode/cpp/calc_projections_c/CMakeLists.txt, _LowLevelCode/cpp/combine_sqw/CMakeLists.txt, _LowLevelCode/cpp/hdf_mex_reader/CMakeLists.txt, _LowLevelCode/cpp/mtimesx_horace/CMakeLists.txt, _LowLevelCode/cpp/recompute_bin_data/CMakeLists.txt, _LowLevelCode/cpp/sort_pixels_by_bins/CMakeLists.txt
Update to make things consistent with https://github.com/pace-neutrons/Herbert/pull/201.
This is a less disruptive change than in Herbert and should be merged first.
Fixes #294
=> Build mex libraries directly into DLL directory

_test/test_sqw/test_PixelData.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/private/compute_bin_data_mex_.m
When dirty PixelData pages were read in, even if those pages were not edited, the pages were being re-written to disk.
A new dirty_page_edited_ flag has been added to PixelData to prevent the pages being written again if they weren't edited.
Fixes #310
=> Prevent re-writing of dirty PixelData pages

_test/test_sqw/test_binary_ops.m, horace_core/sqw/@sqw/private/binary_op_manager_single.m
Adds a suite of tests for SQW binary operations. 
The tests written are not meant to test that the individual binary operation implementations are correct e.g. `plus`, `minus`. The point of the tests is to ensure that performing binary operations with SQW objects behaves as it should, i.e. correct type returned, no errors raised, errors raised where they should be.
Fixes #304
=> Add tests for SQW binary operations

_test/test_sqw/test_PixelData_operations.m, horace_core/sqw/PixelData/@PixelData/do_unary_op.m, horace_core/sqw/PixelData/@PixelData/private/compute_bin_data_mex_.m
Fix segfault when running `recompute_bin_data`on an SQW object with more than 1 dimension. 
Also, a quick fix to avoid editing the `PixelData` instance when calling `PixelData.do_unary_op` with a return argument.
Fixes #308
=> Fix mex error when applying unary ops to multi-dimensional SQW

documentation/smg/08_setting_up_jenkins_ci.md, tools/bash/clone_herbert_branch.sh, tools/build_config/Jenkinsfile, tools/pwsh/clone_herbert_branch.ps1
This PR adds a `HERBERT_BRANCH` parameter to our Jenkins pipelines. When triggering builds we now have the option to select a given Herbert branch or tag to clone from GitHub. *Nightly builds will still use the last successful Herbert nightly package*.
This PR also moves the parameter definitions in the Horace pipelines into the Jenkinsfile. This better documents what our parameters are and keeps our pipeline in sync with one another.
Fixes #332
=> Extend CI pipelines to build against Herbert branch or tag

tools/build_config/Jenkinsfile
The function was previously only ever returning an empty string. There's
some weirdness when setting/returning variables from within a
withCredentials block.
This fix should get the pipelines back up and running properly
=> Fix get_agent function in Jenkinsfile

tools/build_config/Jenkinsfile
This was causing a null value to be set as the default Herbert branch for the nightly builds.
=> Fix missing return in Jenkinsfile

_test/CMakeLists.txt, _test/disabled_tests.md, _test/test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_parpool.m
The test was timing out on the Windows build server. Hopefully this will be long enough for the test to complete.
Fixes #377
=> Extend gen_sqw_parpool test timeout to 25 mins

tools/build_config/build.ps1
Allow CMake to pick the default compiler, this will be the most up-to-date Visual Studio on the system. The script still allows one to
specify a specific Visual Studio version
This was causing issues when attempting to use the build script to re-build targets originally build with Visual Studio 2019. The script
would default to attempting to rebuild with 2017, which would upset CMake and cause an error.
Fixes #356
=> Do not default to Visual Studio 2017 in build.ps1

horace_core/configuration/@hor_config/hor_config.m
Since many operations still have not been adapted for file-backed data, this value should be as high as possible such that we're not paging any data for the time being.
Fixes #406
=> Increase default pixel page size setting

_test/test_sqw/test_PixelData.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/get_abs_pix_range.m, horace_core/sqw/PixelData/@PixelData/get_pixels.m, horace_core/sqw/PixelData/@PixelData/mask.m, horace_core/sqw/PixelData/@PixelData/move_to_page.m
This PR changes the behaviour of `PixelData.get_pixels` such that it indexes into the full, file-backed, pixel array. The previous behaviour was to index the currently cached page of pixels (which may or may not have been the full array). These changes are in line with the ADR written in https://github.com/pace-neutrons/Horace/issues/409.
To aid in the new implementation of `get_pixels` I've added the `PixelData.move_to_page` method. This allows you to move to an arbitrary page of the pixel data, rather than having to call `.advance()` n times.
I've also changed the behaviour of `.advance` so that it does not immediately load the next page of pixels. The pixels are not loaded until data is requested from that page. This makes it cheap to loop through pixel pages if you don't necessarily …
=> Make PixelData.get_pixels retrieve data using absolute index

documentation/smg/10_build_release_process.md, documentation/smg/12_deploying_releases_to_GitHub.md, documentation/smg/13_smoke_testing.md
This PR adds an SMG for the process of creating releases to be deployed to GitHub.
This constituents a draft of my vision for what the release-deploy process could be. I'm happy to hear suggestions/improvements/changes to the process outlined in this PR. 
There's also a section I need to add on deploying patch releases, as that is slightly different to the process laid out in this PR.
This, creation of deploy pipelines and https://github.com/pace-neutrons/ci-release-deploy/pull/1 fixes #73.
=> Add release and deploy SMG

documentation/adr/0016-use-double-array-in-memory-for-pixel-data.md, documentation/adr/0017-separate-absolute-and-relative-indexing-APIs-in-pixel-array.md
Adds an ARD record for the decisions made r.e. absolute/relative indexing into an SQW object's pixel array.
Fixes #408
=> Write ADR for pixel data absolute/relative indexing

_test/test_sqw/test_PixelData.m, horace_core/configuration/@hor_config/hor_config.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/get_data.m, horace_core/sqw/PixelData/@PixelData/get_pixels.m, horace_core/sqw/PixelData/@PixelData/private/get_idxs_in_current_page_.m
This PR updates `PixelData.get_data` to use absolute indexing rather than relative (to page) indexing.
This brings `get_data`'s API up-to-date with `get_pixels` and the API described in the ADR added in https://github.com/pace-neutrons/Horace/pull/409.
Fixes #413
=> Update PixelData.get data to use absolute indexing

horace_core/sqw/PixelData/@PixelData/get_data.m, horace_core/sqw/PixelData/@PixelData/get_pixels.m
Update the help in `PixelData.get_data` to reflect the new behaviour introduced in https://github.com/pace-neutrons/Horace/pull/415.
Fixes #418.
=> Function help in PixelData.get data is incorrect

documentation/smg/12_deploying_releases_to_GitHub.md
Hopefully this makes more explicit the purpose the Git SHAs in the deployment process.
Fixes #437 .
=> Add some clarification on Git SHA in deploy SMG

_test/CMakeLists.txt, _test/common_functions/FakeFAccess.m, _test/common_functions/benchmark_function.m, _test/test_sqw_class/test_equal_to_tol.m, _test/test_sqw_class/test_sqw_constructor.m, _test/test_sqw_class/test_sqw_copy.m, admin/validate_horace.m, horace_core/sqw/@SQWDnDBase/SQWDnDBase.m, horace_core/sqw/@sqw/copy.m, horace_core/sqw/@sqw/equal_to_tol.m, horace_core/sqw/@sqw/private/make_sqw.m, horace_core/sqw/@sqw/private/make_sqw_detpar.m, horace_core/sqw/@sqw/private/make_sqw_header.m, horace_core/sqw/@sqw/private/make_sqw_main_header.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/PixelData/@PixelData/equal_to_tol.m
Initial SQW constructors for the core use cases
Deliberately retain current the original class attributes in first phase of rewrite. These will be replace/updated later in the process.
Base class is not used for anything at the moment so cleaned out the demo props it had contained.
=> SQW constructor creation

tools/build_config/build.ps1
Should fix build scripts when Horace is within a directory containing spaces.
Similar change for Herbert in progress.
Fixes #448
=> Fix missing quotes in build.ps1 commands

documentation/smg/08_setting_up_jenkins_ci.md, tools/build_config/Jenkinsfile
If you use Groovy string interpolation when passing credentials to a
shell command, the secret will be executed in plain text on the agent.
The Jenkins logs will still mask the credentials, but any command
logging on the agent machine will leak the secret.
Using the environment variable set by the withCredentials block means
the command does not contain the secret, any command logs will only show
an environment variable was accessed.
See https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#interpolation-of-sensitive-environment-variables.
=> Do not use Groovy interpolation for Jenkins creds

_test/test_dnd_class/test_binary_ops.m, _test/test_sqw/test_PixelData_binary_ops.m, _test/test_sqw_class/test_binary_ops.m, horace_core/sqw/@DnDBase/DnDBase.m, horace_core/sqw/@DnDBase/binary_op_manager_single.m, horace_core/sqw/@DnDBase/mask.m, horace_core/sqw/@DnDBase/sigvar.m, horace_core/sqw/@DnDBase/sigvar_size.m, horace_core/sqw/@d2d/d2d.m, horace_core/sqw/@sqw/binary_op_manager_single.m, horace_core/sqw/@sqw/mask.m, horace_core/sqw/@sqw/private/header_average.m, horace_core/sqw/@sqw/private/recompute_urange.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/@sqw_old/private/binary_op_manager_single.m, horace_core/sqw/PixelData/@PixelData/do_binary_op.m, horace_core/sqw/PixelData/@PixelData/private/binary_op_sigvar_.m
Move the binary operation manager into the DnD base class and update logic to handle DnD classes in SQW and PixelData settings.
Split binary op tests between SQW and DND test files to match use cases.
[any changes to the InferiorClasses pattern will be made under a separate PR]
=> Add Binary Ops to D2D object

_test/test_mex_nomex/test_main_mex.m, _test/test_sqw/test_PixelData.m, _test/test_sqw/test_sqw_dnd_eval.m, _test/test_sqw/utils/concatenate_pixel_pages.m, _test/test_sqw_file/test_faccess_sqw_prototype.m, _test/test_sqw_file/test_faccess_sqw_v2.m, _test/test_sqw_file/test_faccess_sqw_v3.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/equal_to_tol.m
This PR removes the `size` overload from the `PixelData` class.
I did a grep through code to try and find all the calls to `size` on `PixelData` objects - hopefully I've caught them. Most of them were in tests anyway.
Alternatives to using `size`:
```matlab
size(pix, 1) == size(pix.data, 1);  % should be avoided in production code as structure of `.data` is not guaranteed
size(pix, 2) == pix.num_pixels;
```
At the point we need it, we will want to add a method like `pix.num_fields` (which would usually be 9), so we can avoid doing `size(pix.data, 1)`.
Addresses #481
=> Remove size overload on PixelData class

_test/test_sqw/test_PixelData_operations.m, _test/test_sqw/test_mask.m, documentation/release_notes/v3.5.1.md, horace_core/sqw/@sqw/mask_pixels.m, horace_core/sqw/@sqw/mask_random_fraction_pixels.m, horace_core/sqw/@sqw/mask_random_pixels.m, horace_core/sqw/PixelData/@PixelData/compute_bin_data.m, horace_core/sqw/PixelData/@PixelData/mask.m, horace_core/sqw/PixelData/@PixelData/private/compute_bin_data_matlab_.m, horace_core/sqw/PixelData/@PixelData/private/compute_bin_data_mex_.m
This PR fixes and adds tests for `sqw.mask_pixels` which was failing as it had not been adapted to use `PixelData.mask` (see 
eae2783).
I also noticed that `PixelData.compute_bin_data` was throwing an unexpected error if the `PixelData` object contained no pixels. I took the decision to just return empty arrays in this case, another option was to throw an error - what do you think?
Addresses #500 
_Once this PR is merged into `rel_3_5` I'll open another PR to merge it into `master`_
=> Mask random pixels does not work

_LowLevelCode/cpp/sort_pixels_by_bins/sort_pixels_by_bins.cpp, _LowLevelCode/cpp/sort_pixels_by_bins/sort_pixels_by_bins.h, _test/test_algorithms/test_cut.m, _test/test_rebin/test_rebin.m, horace_core/algorithms/@cut_data_from_file_job/cut_data_from_file_job.m, horace_core/algorithms/cut.m, horace_core/sqw/@sqw/private/cut_accumulate_data_.m, horace_core/sqw/@sqw/private/cut_single.m
This PR restores the ability to take out-of-memory cuts from an SQW file. This is useful when taking cuts where the output cut is too large to fit in memory. I've not implemented a new process for these types of cut, I've simply dropped in the old method using a `pix_combine_info` object.
The out-of-memory cuts work by:
1) Looping over input file's pixels
2) Retaining only the pixels in the range of the cut
3) Saving the pixels to be retained in a temporary file, along with an `npix` array that specifies which pixels belong in which bin (of the output cut)
4) Generating an SQW object (`sqw_cut_obj`) whose pixels are replaced with a `pix_combine_info` object (this holds a reference to the temp files and info required to combine them)
5) When `sqw_cut_obj` is saved, …
=> Implement file to file cuts with temp files using file backed pixel data

documentation/adr/0019-update-release-notes-every-pr.md, documentation/adr/0020-use-c-mex-api.md
This PR adds an ADR explaining our decision to prefer the C Mex API over the C++. 
I've left a TODO in the ADR in the hope that a reviewer can provide an example of where the C++ API was too restrictive for our use-case. I know we discussed such a case existing, does anyone have a concrete example of this?
Addresses #484
=> Add ADR for decision to prefer C Mex API over C++

CMakeLists.txt, _test/CMakeLists.txt, admin/CMakeLists.txt, cmake/FindHerbert.cmake, cmake/horace_FindHDF5.cmake, documentation/adr/0004-cpp-tests-in-separate-projects.md
These changes in Horace reflect those made to Herbert in https://github.com/pace-neutrons/Herbert/pull/290. It will enable Horace to use the `VS_DEBUGGER_ENVIRONMENT` property on its C++ tests, so you do not need to set environment variables to run tests in Visual Studio.
The changes made to `PACE_AddCppTest.cmake` in https://github.com/pace-neutrons/Herbert/pull/290 are what will fix the Visual Studio issue. This PR defines the `Horace_ROOT` variable that `PACE_AddCppTest.cmake` uses.
Addresses https://github.com/pace-neutrons/Herbert/issues/213
=> Replace uses of CMAKE_SOURCE_DIR with Horace_ROOT

horace_core/sqw/file_io/@combine_sqw_pix_job/private/read_pix_for_nbins_block_.m
This is simple fix for the bug, being there for ages, and appearing if one have `nochange` mode and number of files is bigger then 8. Do not know how to write a unit test for it as our current tests are checking 6 files, 8 will be more expensive and in a way useless but separate test is difficult to derive.  Performance tests would be caching it.
=> Bug in combine

CMakeLists.txt
In conjunction with https://github.com/pace-neutrons/Herbert/pull/300 exclude Herbert
=> Make Horace linting ignore Herbert root

tools/build_config/Jenkinsfile
Add default values to the Jenkinsfile to avoid assigning `null` in the environment
=> Set default values to avoid error

_test/test_sqw/test_PixelData.m, horace_core/admin/modify_pix_ranges.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/get_data.m, horace_core/sqw/PixelData/@PixelData/private/check_pixel_fields_.m, horace_core/sqw/PixelData/@PixelData/private/logical_to_normal_index_.m, horace_core/sqw/PixelData/@PixelData/set_data.m
As part of my work on #550 I need a `set_` method on pixels that can set field data across page boundaries. This method is the inverse of `PixelData.get_data` so they share a fair amount of logic.
refs #550
=> Add PixelData.set_data method

_test/test_sqw/test_PixelData.m, _test/test_sqw_file/test_hdf_pix_group.m, _test/test_sqw_file/test_sqw_formats_factory.m
Fix `assertExceptionThrown` printing since https://github.com/pace-neutrons/Herbert/pull/334
=> Fix erroneous print

documentation/adr/0020-use-c-mex-api.md, documentation/adr/0021-errors-and-warnings.md, documentation/adr/0022-use-keyword-args.md, documentation/adr/0023-error-format.md
Create ADR 23 outlining decisions made around error identifiers in PACE.
Also update surrounding ADRs to match format and link correctly.
=> Add ADR 23

horace_core/sqw/@sqw/disp2sqw_eval.m, horace_core/sqw/file_io/@sqw_binfile_common/sqw_binfile_common.m, horace_core/utilities/@sqw/symmetrise_sqw.m
Simple solution for simple bug. `varargin` is empty if no optional arguments are available, so simple fix to the issue
=> disp2sqw eval bug

horace_core/spaghetti_plot.m
Fix bug in generating 1D cuts from the 2D slices normally output by `spaghetti_plot`.
First, originally the 2D cuts were `d2d` objects, and 1D cuts were made from this, but now we use `sqw` to make things more accurate. Also, there is a check if there are no pixels in the 2D which previously caused an exception.
Fixes #661
=> Fix spaghetti_plot 1D if no data in 2D cut bug

documentation/smg/02_development_environment.md
I have copied the PACE demo from babylon/Scratch/Perring to the SAN disk. This PR additionally documents this location for new users, to provide info on accessing the Windows server and its useful network mappings, and to give instructions for copying it back to babylon in the event that the original scratch directory is not available.
Provided also for review of the instructions.
=> add permanent location for demo

_test/common_functions/@SQW_GENCUT_perf_tester/large_cut_nopix_task_performance.m, _test/common_functions/@SQW_GENCUT_perf_tester/large_cut_pix_fbased_task_perfornance.m, _test/test_gen_sqw_workflow/CUTS_PERF_PerfRez.xml, _test/test_gen_sqw_workflow/test_cuts_performance.m
this small bug should not affect anybody, as the test performance should  be run automatically anywhere at the moment. 
Despite that, the mode when the test verifies the gen_sqw performance was disabled so I have enabled it. 
It does not mean it should not be fixed to simplify development in a future
=> figing test_cuts_performance in production (jenkins) mode

_test/test_sqw_file/test_serialize_deserialize.m
Change reference data which contains inf in img_db_range
Modern code should not contain such data and do not know how to treat them
=> fixing test_refine_crystal_1 

cmake/PACE_Docs.cmake
With the removal of `[NULL]` and the addition of the hidden doctrees, this workaround code is no longer necessary.
=> Remove unnecessary build code for docs

.github/workflows/push_docs_stable.yml, .github/workflows/push_docs_unstable.yml
Adds a github action to build and push the user documentation to a website.
* Unstable docs are built and published whenever a commit is made to *master* (e.g. when a PR is merged to master).
* Stable docs are built when a release is published.
The published web documentations can be accessed using:
https://pace-neutrons.github.io/Horace/stable/ - documentation corresponding to the latest release
https://pace-neutrons.github.io/Horace/unstable/ - documentation for the latest `master`
https://pace-neutrons.github.io/Horace/v3.6.0/ - documentation for specific release versions
At present the released versions with documentation are: `3.5.1`, `3.5.3` and `3.6.0`.
=> Github actions docs build and push

documentation/smg/18_ci_user_docs_build.md, tools/build_config/Jenkinsfile, tools/build_config/build.ps1, tools/build_config/build.sh
This PR removes the publishing of user docs from the Jenkins / Anvil CI, in preference to using github-actions, introduced in #772.
The documentation are still built in Jenkins, and the docs artifact can still be downloaded there.
The PR also adds a SMG document describing the changes.
=> User docs CI

_test/test_mex_nomex/test_fake_sqw_bin_pix.m
Minor fix to make `test_fake_sqw_bin_pix` use `skipTest`
=> test_fake_sqw_bin_pix use skipTest function

herbert_core/applications/multifit/@mfclass/private/multifit_lsqr_par.m, herbert_core/applications/multifit/MFParallel_Job.m
Change in `split_sqw` not mirrored in other splittings leading to crash
=> Fix issues with parallel multifit

_test/test_main_header/test_main_header_operates_properly.m
Add test to ensure `datetime` wraps correctly, along with some simplification.
=> Add datetime wrapping test

admin/horace_install.m, herbert_core/herbert_init.m, horace_core/horace_off.m
Fix to removing herbert_off for horace_install and other misc. Should be hotfix.
Still not sure where 
> Function herbert_off.m not found in /home/jacob/PACE/HorBack/herbert_core
> Clearing rootpath and subdirectories from Matlab path in any case
Is coming from, but should be simple fix
=> Fix horace_install with herbert_off gone

horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m
Remove the forced recalculation of ranges on tmp-pix (not tmp sqw) backed objects
=> Remove recalc range from finalise

_test/test_sym_op/test_symop.m, _test/test_symmetrisation/test_symm.m, herbert_core/utilities/geometry/box_intersect.m, horace_core/sqw/@sqw/symmetrise_sqw.m, horace_core/symop/@Symop/Symop.m, horace_core/symop/@SymopGeneral/SymopGeneral.m, horace_core/symop/@SymopIdentity/SymopIdentity.m, horace_core/symop/@SymopReflection/SymopReflection.m, horace_core/symop/@SymopRotation/SymopRotation.m
- Converts `symmtrise_sqw` to use `Symop`s rather than reflection plane vectors. (Legacy supported)
- Adds experimental rotational symmetry reduction (though untested as yet)
- Corrects spelling of `plain` to `plane` in `box_intersect`
=> 1003 symop symmetrise

tools/build_config/Jenkinsfile
ANVIL Python limited to 3.6, also making request to update to 3.10/3.11 alongside this, hopefully temporary.
=> Fix sphinxmatlab version to 0.14 to avoid Python 3.8 features

_test/test_sqw_class/test_equal_to_tol.m, horace_core/sqw/@sqw/private/equal_to_tol_internal_.m, horace_core/sqw/PixelData/@PixelDataBase/equal_to_tol.m
Restore masking bins on `fraction`al `equal_to_tol` between `PixelData` objects
Fixes #1033
=> Restore bin masking on pix `equal_to_tol`

_test/test_mpi_wrappers/test_parallel_config_and_clusters_factory.m, herbert_core/classes/MPIFramework/@ClusterSlurm/ClusterSlurm.m, herbert_core/classes/MPIFramework/@ClusterWrapper/ClusterWrapper.m, herbert_core/classes/MPIFramework/@parallel_config/parallel_config.m, horace_core/configuration/@hor_config/hor_config.m, horace_core/configuration/@hpc_config/hpc_config.m
Standardise names between different configurations:
- `par_threads` -> `parallel_threads`
- `known_clust_configs` -> `known_cluster_configs`
- Removed `accumulating_process_num`
- Moved `wkdir_is_default` and `is_auto_parallel_threads` to hidden blocks
- Made internal references to other configs be the actual name of the config.
Fixes #1047
=> 1047 fix var names

_LowLevelCode/cpp/CommonCode.h, _LowLevelCode/cpp/combine_sqw/fileParameters.h, _LowLevelCode/cpp/cpp_communicator/input_parser.h, _LowLevelCode/cpp/serialiser/cpp_serialise.hpp
GCC 13 doesn't seem to automatically include `cstdint` causing compilation errors
=> Fix C++ on GCC13

_LowLevelCode/cpp/serialiser/c_deserialize.cpp, _LowLevelCode/cpp/serialiser/c_serialize.cpp, _test/test_serializers/test_cpp_deserialize.m, herbert_core/utilities/misc/hlp_deserialize.m, herbert_core/utilities/misc/hlp_serialize.m
Just renames error IDs, other changes and renames covered in #1064 
Fixes #817
=> Make C and MATLAB serialisers return corresponding errors

_test/test_serializers/test_serializable_class_2.m, herbert_core/utilities/classes/@serializable/private/from_struct_.m
which just removes all unnecessary checks. The `test_IX_experiment` which was erroneously faling before is working fine
=> simple fix

horace_core/sqw/@sqw/sqw.m
SQW's `get_new_handle` was altered in merge, this prevents the crash
=> Fix missing ldr on return

CMakeLists.txt, _LowLevelCode/cpp/test/get_ascii_file.tests/CMakeLists.txt, cmake/shared/PACE_FindGTest.cmake
Fix CMake policies and update `googletest` to avoid CMake generated warnings.
Fixes #568
=> Fix CMake warnings

_test/test_sqw_class/test_equal_to_tol.m, horace_core/sqw/PixelData/@PixelDataBase/equal_to_tol.m
- Add test comparing mem & fb are different if nth page is modified.
- Fix reporting of column name
Related to issue raised by @abuts about comparisons between mem & filebacked pix not checking all pages.
=> Add test comparing mem & fb diff paged; fix reporting of column name

horace_core/sqw/@sqw/split.m
Use `get_fields` to load all run_idx.
Fixes #1119
=> Make split fb-safe

_test/test_sqw_class/test_equal_to_tol.m, herbert_core/utilities/maths/equal_to_tol.m
Get rid of intermediate failures with `datetime` mismatches by comparing actual times. If within one minute of each other, considered equal.
=> Fix date time comparison once and for all

_test/test_sqw_class/test_section.m, horace_core/sqw/@sqw/section.m
Add filebacked calculation capabilities to `sqw.section` to filter pixels, along with corresponding unit test.
Fixes #1066
=> 1066 Add filebacking to section

horace_core/sqw/@sqw/symmetrise_sqw.m, horace_core/symop/@Symop/Symop.m, horace_core/symop/@SymopReflection/SymopReflection.m, horace_core/symop/@SymopRotation/SymopRotation.m
Transform symmetry irreducible region according to current projection to symmetrise in the basis of the current projection rather than the cartesian lattice basis. 
Only currently considering lattice-based projections (`ortho_proj`) may have trouble with others. Will consult and add warning as necessary.
Needs unit tests to prove
Fixes #1039
=> Make symmetrise operate in projection basis

horace_core/GUI/horace.m
Object is in local workspace and `get` causes issues.
=> Replace get with object name directly (Horace GUI Fixes)

_test/test_algorithms/test_parallel_cut.m, _test/test_symmetrisation/test_symm.m, horace_core/algorithms/@cut_data_from_file_job/private/accumulate_pix_to_file_.m, horace_core/sqw/@sqw/private/cut_accumulate_data_.m, horace_core/sqw/@sqw/private/cut_single_.m
Make file-backed cut use `cut_to_file` implementation with a `TmpFileHandler`-managed file as `outfile` when object larger than cut in memory (as determined by `PixelDataBase.do_filebacked`) and no `outfile` specified.
Leave `PixelDataFileBacked` based one to be explicitly overridden by developer to use only for debugging purposes. 
Use TmpFileHandler to manage SQW file for `cut_to_file` with no supplied `outfile`.
Cut with `outfile` unchanged.
Fixes #1111
=> Optimise filebacked cut

_test/test_symmetrisation/test_symm.m, horace_core/sqw/@sqw/symmetrise_sqw.m
Rotational symmetry requires properly defined projection to work, default to hkl basis.
Add tests for rotational reduction (just of functionality, need proper data tests later)
Fixes #1191
=> Fix symmetrise with proj

herbert_core/herbert_init.m, horace_core/horace_init.m
`herbert_init` tries to load `hor_config` as part of the `optimal_config` loader. This causes a crash as `hor_config` has not been included in the search path yet. This is called as part of `horace_init` anyway.
Fixes #1204
=> Stop `herbert_init` trying to load `hor_config`

horace_core/Tobyfit/tobyfit_DGdisk_resconv_init.m
In issue #1135 @abuts  identifies a slowdown due to refetching runmap_id from its parent SQW within an arrayfun. This PR follows his suggestion to factor the fetch outside of the arrayfun.
=> Modify runmap_id code to remove slowdown

_test/test_experiment/test_experiment_methods.m
In ticket #906 test test_experiment/test_experiment_methods:test_single_sample_sets_up_array was uncertain about what it was testing and whether that behaviour is correct. This PR confirms that if you set an existing Experiment samples container to a single sample, it will replicate that sample to the correct number of runs and completely overwrite the Experiment samples with that replication. This state is tested and the skipTest for this uncertainty is removed.
=> Make test for assignment of samples explicit that it replicates the individual input

horace_core/sqw/@SQWDnDBase/mask_points.m, horace_core/sqw/coord_transform/@line_proj/private/transform_img_to_hkl_.m
`dnd` objects were being treated in the old (pre-SQW-rewrite) way and `mask_points` hadn't been updated to address this, causing failures in creating an `mfclass` wrapping a `dnd`
Also issue with inverse order of operations on `transform_img_to_hkl`
Fixes #1230
=> Fix issue with multifit on dnd objects

documentation/user_docs/docs/Horace_manual.rst, documentation/user_docs/docs/Unsorted.rst, documentation/user_docs/docs/manual/Advanced_Multifit.rst, documentation/user_docs/docs/manual/Multifit.rst
Migrate parallel fitting to regular multifit docs
Move advanced multifit from main docs to `unsorted` pile (as backup only)
=> Remove Advanced multifit from main docs

_LowLevelCode/cpp/serialiser/c_deserialize.cpp
Remove special case and standardise `if` block, adding comment to describe reasoning.
This is not an issue in `c_serial_size` as it has the following block:
```
if (nFields > 0) {
mxArray* arr = const_cast<mxArray *>(input);
mxArray* conts;
mexCallMATLAB(1, &conts, 1, &arr, "struct2cell");
data_size = get_size(conts);
}
```
Fixes #1328
=> Simplify c_deserialise code

herbert_core/admin/tmp_dir.m
this change should remove all spaces from the name of default working folder
=> no spaces in wk_dir folder name

_test/test_mpi_wrappers/test_cluster_wrapper.m, herbert_core/admin/tmp_dir.m, herbert_core/classes/MPIFramework/@ClusterWrapper/ClusterWrapper.m, horace_core/horace_off.m
Fixes #1390.  Number of issues have been identified on iDAAAS related to path-es stored/not stored in MATLABPATH and other enviromental variables. Normally it is invisible but becomes an issue when one dynamically switches from one Horace version to another. Hopefully all fixed now -- switching with parallel cluster works
=> userpath provided to workers

_test/test_change_crystal/test_refine_crystal.m, horace_core/lattice_functions/refine_crystal.m
Return a structure from `refine_crystal` containing fit error estimates.
Fixes #770
=> Return error estimates from `refine_crystal`

_test/test_sym_op/test_cut_sqw_sym.m
- Modify cut range of no-dup to ensure pixels exist in resulting cut
- Make reflection cut `data` rather than `data2` and reflect across X axis to ensure that both regions of the cut actually contain pixels
Fixes #1387
=> Modify tests to ensure pixels

documentation/smg/22_unique_references_container.md, herbert_core/utilities/classes/@unique_references_container/unique_references_container.m
In #1157 it is suggested that the Matlab singleton pattern is not used for unique_references_container. This is not the case, but the pattern is adapted so that a set of templated singletons, one per data type, are stored in the same class.
To document this, as suggested by Jacob, an SMG document, no.22, is added with this PR. The document is referenced in the code for the container.
As code is changed (even though only in comments) the DO_NOT_CI label is not applied.
=> Document use of Matlab singleton pattern in unique_references_container

_test/test_TF_components/test_tobyfit_cuts.m, _test/test_TF_let/test_tobyfit_let_cuts.m, _test/test_multifit/test_multifit_horace_1.m
Add simple tests to verify file-backed fitting algorithms for use in #760 refactor of Tobyfit and as part of verification of #1420
Tobyfit currently does not work with file-backed objects and fails with a size mismatch in assignment in `tobyfit_*_resconv`, so these tests remain disabled for now. 
The unskipped multifit test is the multifit equivalent of these skipped Tobyfit tests which use filebacked sqws in the calculation and are the supporting evidence for the skipped Tobyfit tests.
As part of #760 they will be used in developing file-backed Tobyfit.
Fixes #1423
=> Add fitting file-backed tests for Toby/multifit

_test/test_dnd_class/test_migrated_apis.m, _test/test_sqw_class/test_migrated_apis.m, _test/test_sqw_pageOpMethods/test_join.m, admin/run_docify.m, herbert_core/admin/parse_path.m, herbert_core/classes/data_loaders/@rundata/private/serialize_.m, herbert_core/utilities/maths/array_common.m, horace_core/algorithms/collect_sqw_metadata.m, horace_core/algorithms/read_horace.m, horace_core/sqw/@sqw/join.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/coord_transform/@line_proj/private/eq_.m, horace_core/sqw/page_operations/PageOp_join_sqw.m
This should be looked at after #1428 is merged. 
This is @oerc0122-style PR, containing only one change. `join` opeation for `sqw` object made static and various small changes related to search for join within the code base and fixing various small issues in the code (like typos) identified while looking for `join` within the code. 
I normally would not do such PR, because such changes are part of development, but because these changes produce working code at this stage, I do not mind making them into a separtate PR.
=> join is static sqw method

horace_core/configuration/@hpc_config/hpc_config.m
Missing semi-colon meant that Sphinx could not find the class constructor method and hangs.
=> Fix docs bug - missing semicolon

_test/test_sym_op/test_cut_sym_cube.m, horace_core/algorithms/cut.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m, horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/finish_dump_.m, horace_core/sqw/PixelData/@PixelDataMemory/PixelDataMemory.m, horace_core/symop/@Symop/Symop.m
This PR should be condidered #1435 is merged.  It addresses ticket #1403
These change remove all instances of internal write handle and `get_new_handle` functions from code base so all filebacked operations are performed through external write handle connected with PageOp class.
=> removing old interface to write handle

_test/test_sqw_pageOpMethods/test_sigvar_set.m, horace_core/sqw/@sqw/sigvar_set.m, horace_core/sqw/page_operations/PageOp_sigvar_set.m
This is PageOp implementation of sigvar_set algorithm, expanding current implementation to object with pixels including filebacked pixels. 
In addition, previous implementation was apparently incorrect as pixel's variance was assigned image variance though consistent asignment should be `img_variance.*npix`
=> sigvar set

_test/test_algorithms/test_parallel_cut.m
The issue that was previously reported on the Jenkins machines could not be reproduced, as such enabling the tests seems to be the only need at the moment.
Fixes #1172
=> Enable parallel cut tests

herbert_core/classes/instrument_classes/instrument/@IX_experiment/IX_experiment.m, horace_core/change_crystal.m, horace_core/sqw/file_io/@const_blocks_map/const_blocks_map.m, horace_core/sqw/file_io/@const_blocks_map/private/init_map_.m, horace_core/sqw/file_io/@sqw_binfile_common/put_headers.m, horace_core/sqw/file_io/@sqw_serializer/private/serialize_.m
I've enabled legacy alignment for legacy files as need this for running my tests. As we would not support legacy files for much longer and the changes will hopefully will be rarely used, I am not writing unit tests for these changes relying on existing tests to pass.
=> legacy alignment for legacy files

documentation/user_docs/docs/Horace_manual.rst
Fixes #1506 
"Changing Horace Settings" was accidentally duplicated between two toctrees. This simply removes the duplicate.
=> Remove duplicated menu item from toctree

herbert_core/utilities/classes/@object_lookup/rand_ind.m
Add a bit of explanation about `'split'` clarifying what it means.
Related to #1299
=> Add `split` description

herbert_core/utilities/classes/@unique_objects_container/private/add_single_.m, herbert_core/utilities/classes/@unique_references_container/unique_references_container.m, horace_core/sqw/@sqw/sqw.m
As per point 1 of #1157, objects are hashed twice, unnecessarily, for unique_object_containers. This does not happen for these containers themselves, but when used in unique_references_containers, this does happen, and is fixed by this PR.
This investigation also shows that sqw had its experiment_info incorrectly initialised by a property definition rather than a part of the constructor. This may also fix point 2 about clearing the container although as there are no instructions for reproducing it I cannot be certain.
It also shows that unique_references_containers are misleadingly tested by the present tests, as earlier tests perform initialisation of the persistent data which then allow later tests to proceed which would otherwise fail if run in isolation.
=> 1157 fix multiple hashing and experiment initialisation

_test/test_multifit/test_multifit_horace_1.m, _test/test_sqw_pageOpMethods/test_eval.m, herbert_core/applications/multifit/@mfclass/private/multifit_lsqr_ser.m, herbert_core/utilities/classes/@data_op_interface/binary_op_manager.m, herbert_core/utilities/classes/@data_op_interface/binary_op_manager_single.m, herbert_core/utilities/classes/@data_op_interface/data_op_interface.m, herbert_core/utilities/classes/@sigvar/binary_op_manager_single.m, herbert_core/utilities/classes/@sigvar/sigvar.m, horace_core/GUI/bose.m, horace_core/sqw/axes_blocks/@AxesBlockBase/private/bin_pixels_.m, horace_core/sqw/coord_transform/@aProjectionBase/private/may_contribute_.m, horace_core/sqw/coord_transform/@aProjectionBase/private/transform_pix_to_hkl_.m, horace_core/sqw/coord_transform/@line_proj/line_proj.m, horace_core/sqw/coord_transform/@line_proj/private/transform_pix_to_hkl_.m
Addresses Re #1533 -- second part.
bunch of minor bugs fixing `sqw_eval` (and `bose`) for spherical projection.
Nothing more to tell -- unit tests confirming bug  presense now passes so it is the fixture.
Summary of changes (summary by CM from PR review)
- the Bose factor method has been corrected, and a test added that now passes
- in bin_pixels, the shape of the accumulated npix1 array is properly controlled
- handling of the ub_inf_legacy method is altered.
- uniformity of the binary_op_manager methods' interface has been improved
- efficiency of the binary_op managers has been improved by allowing pixel sorting not to be performed when not needed
- comments have been improved
=> fixing sqw_eval for spherical projection

documentation/user_docs/docs/manual/Binary_operations.rst
The main part of the ticket #1472 is done within ticket related to spherical projection but many minor changes and inaccuracies remain. 
As there is the request to make changes to doc separate, I am using this ticket as the base of addressing remaining issues and would be doing doc PR for every block of this changes. 
This PR is about improvements to description of binary operations.
=>  inaccuracies and improvements to docs about binary operations

_test/test_utilities_herbert/test_sawtooth_iarray.m, herbert_core/utilities/maths/sawtooth_iarray.m
Add copious unit tests of Herbert utility function sawtooth_iarray, correct an inconsistency of output array size if the output is empty, and make robust to non-integer input array elements with consistent behaviour with Matlab colon operator.
sawtooth_iarray is called alongside replicate_iarray in some Horace methods that manipulate sqw objects. It is appropriate that sawtooth_iarray is made similarly robust and tested.
The refactoring of sawtooth_iarray has left the speed of the function essentially unchanged. Fairly wide testing yields same time +/- 35%
=> Refactor sawtooth_iarray and add unit tests

_test/test_utilities/test_fix_magnetic_ff.m, horace_core/utilities/@MagneticIons/MagneticIons.m, horace_core/utilities/@MagneticIons/calc_mag_ff.m, horace_core/utilities/@MagneticIons/correct_mag_ff.m, horace_core/utilities/@MagneticIons/form_factor.m
This fixes first part of #1497, allowing Magnetic form factor calculations on `sqw` file with any projection. Trivial fixture and unit test for it. 
The second part -- optimization of this operation is extracted into ticket #1561
=> Generic magnetic form factor

herbert_core/applications/multifit/@mfclass/distribute_fit_data.m
No longer need to distribute `dq_mat` as now computed on-the-fly.
Likewise `qw` is now just a vector and called `en`
Fixes #1563
=> Remove dq_mat from distributed items

horace_core/sqw/@rundatah/private/calc_projections_.m
fixes issue related to incorrect run-id(s) stored in sqw file
causes run_inspector to fail. 
Difficult to write proof as this is bugfix for outdated version
=> incorrect run-id(s) in gen_sqw

_test/test_dnd_class/test_migrated_apis.m, _test/test_multifit/linear_bkgd_sqw.m, _test/test_multifit/test_multifit_horace_1.m, _test/test_sqw_class/test_migrated_apis.m, _test/test_sqw_class/test_smooth.m, _test/test_transformation/test_line_proj_construction.m, _test/test_transformation/test_line_proj_transf_nonorth.m, herbert_core/applications/multifit/@mfclass/private/multifit_lsqr_ser.m, horace_core/lattice_functions/crystal_alignment_info.m, horace_core/sqw/@DnDBase/section.m, horace_core/sqw/@Experiment/remove_legacy_alignment.m, horace_core/sqw/@sqw/compact.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/axes_blocks/@line_axes/line_axes.m, horace_core/sqw/coord_transform/@line_proj/private/build_from_old_data_struct_.m, horace_core/sqw/coord_transform/@line_proj/private/check_combo_arg_.m, horace_core/sqw/coord_transform/@line_proj/private/init_.m, horace_core/sqw/coord_transform/@line_proj/private/projtransf_to_img_.m
This PR contains various minor changes and improvements I have identified while trying to summarize the tests available for `line_proj` and recovery of `line_proj` from legacy aligned data.
Its not directly connected to `legacy_alignment` but still useful as there are small improvements identified while looking at all projection usage. It is committed now not to polute the alignment operations itself.
=> cleaning up projection tests

herbert_core/utilities/general/parse_arguments.m
Solves ticket #1459. It turns out that one field of a structure had be assigned the opposite logical flag to what it should have been when transcribing the original code. The Herbert utility function parse_arguments now has its original functionality again.
=> Correct an error that appeared some time ago when an internal utility function of parse_arguments was refactored.

_test/test_transformation/test_projection_class.m, horace_core/sqw/coord_transform/@projaxes/private/check_and_set_opt_fields_.m
This small change addresses #1617 and allows Horace-3 to accept offset alongside with uoffset within cut algorithm.
=> offset for horace3

_test/test_sym_op/test_cut_sqw_sym.m, _test/test_sym_op/test_cut_sym_cube.m, horace_core/sqw/@sqw/private/cut_accumulate_data_.m
Quick fix for cut-sym with pixels
Partially addresses #1620
=> Add error on attempting to cut-sym with pix

documentation/user_docs/docs/manual/Reshaping_etc.rst
Add documentation for `mask_points`' behaviour with respect to bin-centres vs. bin-edges. 
Fixes #1409
=> Add documentation on `mask_points` behaviour

horace_core/sqw/@sqw/symmetrise_sqw.m
=> Avoid using `cell2mat` in `symmetrise_sqw`

horace_core/sqw/@sqw/symmetrise_sqw.m, horace_core/symop/@SymopRotation/SymopRotation.m
As described in #1510, ultimate issue is symmetrising a non-orthogonal crystal.
This is checked where the projection is given, but if not provided, the default projection accidentally copies non-orthogonal lattice. 
- Extra check put in `SymopRotation.is_irreducible`
- Ensure any points which lie on the plane of the irreducible zone are not transformed
- Make default projection always orthogonal 
Fixes #1510
=> Enforce orthogonal projection for SymopRotation

herbert_core/applications/multifit/@mfclass/private/multifit_lsqr_par.m, herbert_core/applications/multifit/MFParallel_Job.m, herbert_core/classes/MPIFramework/parallel_call/ParallelSQWEval.m, horace_core/sqw/@sqw/distribute.m
- Permit cell arrays of data in `ParallelSQWEval`
- Correctly index regions when assigning local segment to global array with `split_bins`
- Correct source of size of bins to merge (`nelem`) from `wout(i).data.npix` [global array, mostly 0s outside of local segment] to `npix` [local segment]
- Correctly condition `split_bins`
=> Fixes to parallel multifit

_test/test_IX_classes/test_plot_IX_dataset.m, herbert_core/graphics/genieplot_init.m, herbert_core/utilities/classes/@IX_dataset_1d/dd.m, herbert_core/utilities/classes/@IX_dataset_1d/de.m, herbert_core/utilities/classes/@IX_dataset_1d/dh.m, herbert_core/utilities/classes/@IX_dataset_1d/dl.m, herbert_core/utilities/classes/@IX_dataset_1d/dm.m, herbert_core/utilities/classes/@IX_dataset_1d/dp.m, herbert_core/utilities/classes/@IX_dataset_1d/private/plot_1d_nd_.m, herbert_core/utilities/classes/@IX_dataset_1d/private/plot_line.m, herbert_core/utilities/classes/@IX_dataset_1d/private/plot_markers.m, herbert_core/utilities/classes/@IX_dataset_1d/private/plot_markers_errors.m, herbert_core/utilities/classes/@IX_dataset_1d/private/plot_markers_errors_lines.m, herbert_core/utilities/classes/@IX_dataset_1d/private/plot_oned.m, herbert_core/utilities/classes/@IX_dataset_1d/private/types_list_.m
fixes #1619 
array of 1D object is plotted on single plot with line parameters choosen from specified variable. The old behaviour when you may support array of plot parameters is also supported. 
fixed separate plots in 1D case
=> 1D plots are plotted on a single image

_test/test_sqw_pageOpMethods/test_join.m
In #1432 an error has been reported which was subsequently fixed by #1350. The test error was not cleared; this PR does so.
Fixes #1432
=> remove test skip 

_test/test_sqw_file/test_faccess_sqw_v3_3.m, _test/test_sqw_file/test_sqw_formats_factory.m, herbert_core/classes/MPIFramework/@JobDispatcher/JobDispatcher.m, herbert_core/classes/MPIFramework/@JobDispatcher/private/submit_and_run_job_.m, herbert_core/utilities/general/bigtoc.m, horace_core/sqw/@gen_sqw_files_job/private/rundata_write_to_sqw_.m, horace_core/sqw/PixelData/pix_data.m, horace_core/sqw/file_io/@faccess_sqw_v4/put_num_pixels.m, horace_core/sqw/file_io/@sqw_binfile_common/put_pix.m, horace_core/sqw/file_io/@sqw_binfile_common/sqw_binfile_common.m, horace_core/sqw/file_io/@sqw_file_interface/sqw_file_interface.m, horace_core/sqw/file_io/@sqw_formats_factory/private/get_loader_.m, horace_core/sqw/file_io/@sqw_formats_factory/private/get_pref_access_.m, horace_core/sqw/file_io/@sqw_formats_factory/private/get_sqw_type_.m, horace_core/sqw/file_io/@sqw_formats_factory/private/set_pref_accessor_.m, horace_core/sqw/file_io/@sqw_formats_factory/sqw_formats_factory.m, horace_core/sqw/file_io/class_helpers/@pix_data_block/private/put_bindata_in_file_.m, horace_core/sqw/file_io/sqw_formats_factory.m
This contains various debugging changes and modifications done in attempt to fix IDAAAS kernel crash when running gen_sqw job.
Though the reason for crash was the issue in kernel, here I put bunch of convenience changes and fixes made during debugging, namely:
1) logging while running parallel framework. Previous code was botching FUSE file system. In addition, it is exteamly inconvenient to see and look at dots. User wants to get estimate when his parallel job completes and he wants this estimate ASAP, not in half an hour.
2) presumably faster pix writer
3) log while gen_sqw bulds rundata files. Before it was sitting telling user nothing for long time when sqw is build from number of nxspe files. 
4) Possibility to modify `sqw_format_factory` to have different default file writer for …
=> changes to fix idaaas crash

_test/test_dnd_class/test_dnd_cut.m, _test/test_transformation/test_cylinder_proj.m, _test/test_transformation/test_proj_captions.m, _test/test_transformation/test_sphere_proj.m, _test/test_transformation/test_targ_ranges.m, horace_core/sqw/@SQWDnDBase/private/cut_parse_inputs_.m, horace_core/sqw/axes_blocks/@cylinder_axes/cylinder_axes.m, horace_core/sqw/axes_blocks/@cylinder_axes/private/data_plot_titles_.m, horace_core/sqw/axes_blocks/@sphere_axes/private/data_plot_titles_.m, horace_core/sqw/axes_blocks/@sphere_axes/sphere_axes.m, horace_core/sqw/coord_transform/@CurveProjBase/private/check_combo_arg_.m, horace_core/sqw/coord_transform/@aProjectionBase/aProjectionBase.m, horace_core/sqw/coord_transform/@cylinder_proj/cylinder_proj.m, horace_core/sqw/coord_transform/@cylinder_proj/private/get_img_scales_.m, horace_core/sqw/coord_transform/@cylinder_proj/private/transform_cylinder_to_pix_.m, horace_core/sqw/coord_transform/@cylinder_proj/private/transform_pix_to_cylinder_.m, horace_core/sqw/coord_transform/@sphere_proj/private/get_img_scales_.m, horace_core/sqw/coord_transform/@sphere_proj/private/transform_pix_to_spher_.m, horace_core/sqw/coord_transform/@sphere_proj/private/transform_spher_to_pix_.m, horace_core/sqw/coord_transform/@sphere_proj/sphere_proj.m
fixes Re #1670. 
Added bunch of scaling options to spherical and cylindrical projections. 
Looks correct, testing used physical meaning would be beneficial.
=> projection scales

_test/test_sym_op/test_cut_sqw_sym.m, _test/test_sym_op/test_cut_sym_cube.m, documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst, horace_core/symop/@SymopRotation/SymopRotation.m
- Corrected documentation on `cut_dnd`
- Add tests with `cut_sqw` syntax
- Add test of cut-sym from file.
- Fixes issue with cut-sym with non-orthogonal rotational projections
Fixes #1657 
Fixes #1665
=> Address issues with cut-sym and `cut_sqw` syntax

documentation/user_docs/docs/user_guide/Resolution_convolution.rst
- Move theory to the bottom
- Add necessary semi-colons to example scripts
- Reformat to 100char/line
- Modernisation of `ortho_proj`
Addresses part of #1513
=> Make David's requested changes to resconv

documentation/user_docs/docs/user_guide/Horace3_to_4.rst, horace_core/spaghetti_plot.m
Issue was with which space vectors were computed in. 
- Fixed and simplified spaghetti plot using Horace 4 features. 
- One notable difference is that `qwidth` now specifies a full-width rather than a half-width confirmed by Duc to be the original intent, however, this means that `spaghetti_plot` `qwidths` in new Horace are half those of Horace 4. **N.B.** Can back this change out.
Fixes #1710 
Fixes #1709
=> Fix issue with 4.0.0 spaghetti plot

horace_core/utilities/@MagneticIons/getFF_calculator.m
Fixes `getFF_calculator` which broke due to changes in Horace 4.
To test run the examples in the [resolution convolution doc](https://pace-neutrons.github.io/Horace/unstable/user_guide/Resolution_convolution.html#a-worked-example).
Or check the output of:
```
proj = line_proj([1,1,0], [-1,1,0], 'type', 'rrr');
w1 = cut('fe_cut.sqw', proj, 0.05, [-1.05,-0.95], [-0.1,0.1], [80, 100]);
ff_fun = MagneticIons('Fe0').getFF_calculator(w1);
```
between Horace 3 and Horace 4.
`fe_cut.sqw` can be [downloaded here](https://github.com/pace-neutrons/pace-python-demo/blob/main/datafiles/fe_cut.sqw).
=> Fix getFF_calculator for Horace4

horace_core/sqw/@sqw/private/cut_accumulate_data_.m
Fixes #1748. Should apply `SymopIdentity` only if necessary.
=> apply SymopIdentity only if necessary

_test/test_admin/test_horace_install.m, _test/test_admin/test_pc_spec_config.m, admin/horace_install.m, admin/horace_on.m.template
fixes Re #1758 
`horace_install` accepts path to `spinW` package and if such  option is available, modifies `horace_on` to include path to spinW.
Modified unit tests for `horace_install` to remove common code and test new option.
=> horace install accepts spinW path

_test/test_sym_op/test_cut_sym_cube.m, horace_core/sqw/@sqw/private/cut_accumulate_data_.m, horace_core/symop/@Symop/Symop.m
Add extra option to `trust` the `selection` of atoms found by cut to be in the cut range and not check whether it also lies in the irreducible zone. 
Adds test for SymopGeneral cuts.
Fixes #1735
=> Fix SymopGeneral in cut_sym

admin/horace_install.m, demo/demo_FM_spinwaves.m, demo/horace_demo_script.m, demo/horace_spinW_comparison.m, demo/setup_demo_data.m, herbert_core/applications/multifit/@mfclass/set_options.m
fixes Re #1762. 
Old `fit_sqw` interface have been removed from Horace, but left in demo sctipt and now fails. This PR fixes this issue (noticed by user).
There is the question why not to support old `fit_sqw` interface -- it is ugly but works in old scripts. 
There is the question about spinW-Horace comparison as current spinW does not reproduce result obtained from Horace, but formaly demo script is fixed and spinW-Horace comparison is the question for another ticket.
The comparison question redirected to spinW:
https://github.com/SpinW/spinw/issues/207
=> removed old fit_sqw from horace demo

_test/test_change_crystal/test_change_crystal_bragg_coarse.m, horace_core/change_crystal.m, horace_core/lattice_functions/bragg_positions.m
While working with alignment code, I have identified another bug there.  There was a way to change pixels alignment directly in file, which has not been modified similarly to the changes for filebacker/memorybased `sqw` objects.
In other words, `change_crystal` filebacked operation with metadata was missing multiplication by new alignment matrix, added to operations with `sqw` objects earlier
This PR adds unit test demonstrating the bug and fixture for it.
=> bug in alignment

_test/test_admin/test_help.m, herbert_core/applications/docify/help.m, herbert_core/applications/docify/private/check_docify.m
Fixes Horace overloaded `help` command using "docify" for R2024a and newer (where the Matlab internal language function `resolveName` changed package and syntax.
Fixes #1780
=> Fix docify for R2024

_test/test_unique_objects_container/test_unique_references.m, herbert_core/utilities/classes/@unique_references_container/unique_references_container.m
Responding to #1791 this fixes unique_references_container for the existing implementation
A handle was used as a reference handle although it was CoW. Handle now refetched after every update.
=> fix fetch of glc

_test/common_functions/@SQW_GENCUT_perf_tester/gen_sqw_task_performance.m
Fixes Re #1807
Attempt to `runtests test_gen_sqw_workflow` from Matlab session currently fails. 
This small change fixes this issue.
=> enable possibility to run runtests test_gen_sqw workflow from Matlab prompt

_test/common_functions/create_test_instrument.m, _test/test_admin/test_upgrade_file_format.m, _test/test_sqw_file/change_header_test.m, _test/test_sqw_file/test_binfile_v2_common.m, _test/test_sqw_file/test_faccess_sqw_prototype.m, _test/test_sqw_file/test_faccess_sqw_v2.m, _test/test_sqw_file/test_faccess_sqw_v3.m, _test/test_sqw_file/test_faccess_sqw_v3_3.m, _test/test_sqw_file/test_faccess_sqw_v4.m, _test/test_sqw_file/test_horace_binfile_interface.m, _test/test_sqw_file/test_sqw_file_read_write.m, _test/test_sqw_file/test_write_then_read.m, herbert_core/utilities/classes/@unique_objects_container/unique_objects_container.m, horace_core/algorithms/resolution_plot.m, horace_core/sqw/@Experiment/private/build_from_binfile_headers_.m, horace_core/sqw/@Experiment/set_instrument.m, horace_core/sqw/@sqw/private/set_from_old_struct_.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/file_io/@faccess_sqw_v4/get_exp_info.m, horace_core/sqw/file_io/@faccess_sqw_v4/get_sqw.m, horace_core/sqw/file_io/@horace_binfile_interface/horace_binfile_interface.m, horace_core/sqw/file_io/@horace_binfile_interface/private/convert_old_det_forms_.m, horace_core/sqw/file_io/@sqw_binfile_common/get_detpar.m, horace_core/sqw/file_io/@sqw_binfile_common/get_exp_info.m, horace_core/sqw/file_io/@sqw_binfile_common/get_sqw.m
Solves Re #1808. 
After detectors moved into `Experiment` , `get_exp_info` should return `Experiment` with detectors. 
Here I have modified  `get_exp_info` to return `Experiment` with array of detectors and other file-accessors to use this method to build `sqw`. 
I have also extracted old format conversion into new conversion routine into single place and provided unit tests for it.
Also, small bug in load/save `sqw` fixed to avoid  saving/loading detector information twice.
=> get_exp_info returns fully filled experiment

documentation/release_notes/v4.0.2.md, documentation/user_docs/docs/manual/Changing_Horace_settings.rst, documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst, documentation/user_docs/docs/manual/Save_and_load.rst, horace_core/configuration/@hor_config/hor_config.m
Addresses Re #1818. Apparently, filebacked objects are described very badly, so users are confused. 
These changes should inprove the description.
=> Better documentation on filebacked objects

herbert_core/utilities/classes/@data_op_interface/binary_op_manager.m, herbert_core/utilities/classes/@object_lookup/private/split_args.m, herbert_core/utilities/classes/@testsigvar/private/binary_op_manager.m, herbert_core/utilities/general/size_array_split.m
Remove `ok`, `mess` as part of #564 error handling.
Slightly refactor `size_array_split` to flatten function.
Make functions which previously used `ok`, `mess` use the error generated a as a cause.
=> Remove ok, mess from `size_array_split` to avoid error obfuscation

documentation/add/11_sqw_compression.md
Adds an ADD that describes the reasons for having a sqw compression methodology and outlining a proposed solution to the folder \documentation\add
Refers to issue  #1740
=> SQW file compression ADD
