documentation/smg/01_smg.md, documentation/smg/02_development_environment.md, documentation/smg/03_matlab_licensing.md
Document of which Matlab licences are needed on my current understanding of which our of build / test / execution platforms, looking at the range of deployment modes that are being discussed.
Please comment with any errors or additions.
You can view the rendered markdown here: https://github.com/pace-neutrons/Horace/blob/matlab-license/documentation/smg/03_matlab_licensing.md
=> Matlab license requirements documentation

documentation/stp/test-plan.md
Some initial thoughts on a testing strategy for Horace.
All feedback welcomed.
Issue: #37
=> Initial draft of a Horace test plan

documentation/smg/01_smg.md, documentation/smg/06_deployment_process.md
This should do the job, providint the description of the current distribution process.
=> Re #80 the documentation on the current distribution process

documentation/smg/01_smg.md, documentation/smg/07_Windows_Anvil_Node.md
Small document describing current state of the Anvil node
=> 39 anvil win node

documentation/dod/definition_of_done.md
Initial version for discussion.
=> Initial version of DoD

_test/test_sqw/worker_4tests_local.m, horace_core/sqw/@gen_sqw_files_job/private/average_range_process_function_.m
These are small changes, related to changes, made to Herbert tickets [#28](https://github.com/pace-neutrons/Herbert/issues/28) and [36](https://github.com/pace-neutrons/Herbert/issues/36). It should be simple and just merged to Master to maintain Horace integrity vrt Herbert changes.
=> cpp_communicator dependent

documentation/adr/0001-record-architecture-decisions.md, documentation/adr/0002-use-github-for-documentation.md, documentation/adr/0003-use-cmake-for-build.md, documentation/adr/0004-cpp-tests-in-separate-projects.md, documentation/adr/0005-use-gtest-in-cpp-tests.md, documentation/adr/0006-use-jenkins-for-ci.md, documentation/adr/0007-use-herbert-as-library-dependency.md, documentation/adr/0008-use-pipeline-builds.md
New Decision Records covering decisions made regarding Jenkins build pipelines, job structures and the management of Horace/Herbert dependency in them.
=> Jenkins ADR

_test/test_sym_op/test_cut_sqw_sym.m, horace_core/@symop/private/calculate_transform.m, horace_core/@symop/private/check_motion_args.m, horace_core/@symop/symop.m, horace_core/algorithms/@cut_data_from_file_job/private/cut_data_from_file_.m, horace_core/sqw/@sqw/private/cut_sqw_sym_main.m, horace_core/sqw/@sqw/private/cut_sqw_sym_main_single.m
Partially addressing the issues raised in https://github.com/pace-neutrons/Horace/issues/13:
- Fixed a bug whereby `[sym_sqw, sym_cuts] = cut_sqw_sym(sqw, proj, ...)` returned the same information for its first and second outputs instead of the expected vector (or cell array) of symmetry related cuts.
- Fixed a buy where empty symmetry-equivalent cuts could not be handled by `cut_sqw_sym`.
- Added the ability to define a `symop` by its matrix representation.
=> symop improvements

tools/build_config/build.sh
This is a similar fix to the one implemented in Herbert
=> Throw errror in build.sh for unrecognised argument

documentation/smg/08_setting_up_jenkins_ci.md
Update with SCM polling details for nightly builds.
Note: a further update will be required detailing the configuration of Herbert triggered Horace builds
=> Jenkins polling

tools/build_config/Jenkinsfile
Horace equivalent of https://github.com/pace-neutrons/Herbert/pull/78
=> Add names to Jenkins build jobs

documentation/adr/0009-use-standard-naming-for-build-artifacts.md, documentation/adr/0010-package-dependencies-in-repo.md
An ADR for dependency management.
=> Add ADR for dependency management

_test/disabled_tests.md
This is a list of tests that I've been able to identify as disabled. 
Feel free to add to it.
=> Add list of disabled tests to _test folder

tools/build_config/build.ps1
Minor update to build script removing unrequired directory change
=> Remove unrequired directory push

documentation/adr/0010-package-dependencies-in-repo.md, documentation/adr/0011-version-project-with-cmake.md
A plan for versioning the project
=> Add ADR documenting versioning plan for project

documentation/add/07-sqw_redesign.md
Corrects some typos / spelling mistakes and clarifies some questions in the SQW redesign document.
=> SQW design document corrections

documentation/smg/10_how_to_use_the_SAN_area.md
Updates to include Windows script example
=> San storace

_test/common_data/MAPS_IX_detector_array_examples.readme
Add the example IX_detector_arrays provided by @tgperring to the repository
=> Example IX_detector_array instance for development/testing

documentation/smg/10_build_release_process.md
Small addition -- I think, self-explanatory.
=> Added description of the internal release in isis

CMakeLists.txt, _LowLevelCode/cpp/accumulate_cut_c/CMakeLists.txt, _LowLevelCode/cpp/bin_pixels_c/CMakeLists.txt, _LowLevelCode/cpp/calc_projections_c/CMakeLists.txt, _LowLevelCode/cpp/combine_sqw/CMakeLists.txt, _LowLevelCode/cpp/hdf_mex_reader/CMakeLists.txt, _LowLevelCode/cpp/mtimesx_horace/CMakeLists.txt, _LowLevelCode/cpp/recompute_bin_data/CMakeLists.txt, _LowLevelCode/cpp/sort_pixels_by_bins/CMakeLists.txt
This should allow `rel_3_4` to build against Herbert master
=> Update rel branch CMake

_test/CMakeLists.txt, horace_core/algorithms/private/gen_sqw_check_files.m, horace_core/algorithms/write_nsqw_to_sqw.m
This is the Horace part of the ticket, allowing users to have tilde in path
=> tilde in path

_test/test_sqw/test_sqw_dnd_eval.m, horace_core/sqw/@sqw/calculate_qw_bins.m, horace_core/sqw/@sqw/calculate_qw_pixels.m, horace_core/sqw/@sqw/dispersion.m, horace_core/sqw/@sqw/func_eval.m, horace_core/sqw/@sqw/private/replicate_array.m, horace_core/sqw/@sqw/sqw_eval.m
Actually, unit tests for all user function calls, assuring the interface to functions is as described. Minor changes to the Horace code
=> user func calls

documentation/smg/02_development_environment.md
=> Populate new start development environment doc.

documentation/smg/10_build_release_process.md
Before I start adding to/changing parts of this SMG as part of (#331 and #73), I thought it would be good to clean up the formatting a bit. 
I've fixed a few typos, but otherwise haven't made any edits to the actual text. This is mostly line-length limiting.
=> Format build and release SMG

tools/build_config/Jenkinsfile
This is the Horace implementation of https://github.com/pace-neutrons/Herbert/pull/233
Fixes #379
=> Jenkins release pipelines to archive test file with git revision sha

tools/build_config/Jenkinsfile
Merge changes from https://github.com/pace-neutrons/Horace/pull/382 into `rel_3_4`. This will enable us to use release pipelines with the `rel_3_4` branch.
=> rel_3_4: Jenkins release pipelines to archive test file with git revision sha

_test/test_sqw/test_noisify.m, horace_core/sqw/@sqw/noisify.m, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/noisify.m
Allow noisify to operate on paged pixel data.
New pull request to check if old one is corrupt.
=> Allow noisify to operate on paged pixel data

documentation/adr/0017-separate-absolute-and-relative-indexing-APIs-in-pixel-array.md, documentation/adr/0018-algorithm-migration-to-paged-files.md
Document the meeting and decisions reached regarding the implementation of a standard API for algorithms and how that will work with paging.
Resolves #410
=> Paged algorithm API ADR

_test/test_dnd_class/test_dnd_constructor.m, _test/test_dnd_class/test_unary_ops.m, horace_core/sqw/@DnDBase/DnDBase.m, horace_core/sqw/@DnDBase/init_from_file_.m, horace_core/sqw/@DnDBase/init_from_loader_struct_.m, horace_core/sqw/@DnDBase/init_from_sqw_.m, horace_core/sqw/@DnDBase/parse_args_.m, horace_core/sqw/@d0d/d0d.m, horace_core/sqw/@d1d/d1d.m, horace_core/sqw/@d2d/d2d.m, horace_core/sqw/@d3d/d3d.m, horace_core/sqw/@d4d/d4d.m, horace_core/sqw/@sqw/sqw.m
Create constructors for remaining dimensions (0d, 1d, 3d, 4d)
This has moved virtually all the code out of the concrete classes.
=> DnD constructors

_test/test_sqw/test_PixelData_operations.m, _test/test_sqw/test_mask.m, documentation/release_notes/v3.5.1.md, horace_core/sqw/@sqw/mask_pixels.m, horace_core/sqw/@sqw/mask_random_fraction_pixels.m, horace_core/sqw/@sqw/mask_random_pixels.m, horace_core/sqw/PixelData/@PixelData/compute_bin_data.m, horace_core/sqw/PixelData/@PixelData/mask.m, horace_core/sqw/PixelData/@PixelData/private/compute_bin_data_matlab_.m, horace_core/sqw/PixelData/@PixelData/private/compute_bin_data_mex_.m
This ticket to merge changes, done on ticket #500 into master
=> mask random pixels bug master

_test/test_sqw/test_rundata_vs_sqw.m
fixing the issue with master build:  redirected failing tests to Horace/_tests/common
=> Test files location is redirected

_work/Alex_work/orient_crystal.m, _work/RAE_work/run_inspector_videofig.m, horace_core/sqw/@sqw/private/run_inspector_videofig.m
Resave two files with 'incorrect enconding' that MLint failed to parse
=> Convert file encoding iso-8859-1 to utf8

tools/build_config/Jenkinsfile
Add the ability to skip CI based on the `do-not-build` and `do-not-test` PR labels
=> Add skip CI based on labels

tools/build_config/Jenkinsfile
Fix logical order of operations
=> Fix builds skipping tests

documentation/adr/0021-errors-and-warnings.md
=> Create 0021-errors-and-warnings ADR

documentation/user_docs/docs/Advanced_Multifit.rst, documentation/user_docs/docs/index.rst
Migrate Herbert's multifit doc
=> Add advanced multifit doc

_test/disabled_tests.md, _test/test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_herbert.m, _test/test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_parpool.m
Disabled:
test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_herbert
test_gen_sqw_workflow/test_gen_sqw_accumulate_sqw_parpool
Until such a time as they can be stabilised.
=> Disable unstable tests

documentation/smg/17_pixel_data.md, documentation/smg/17_using_pixel_data.md, horace_core/sqw/PixelData/@PixelData/PixelData.m, horace_core/sqw/PixelData/@PixelData/get_data.m, horace_core/sqw/PixelData/@PixelData/get_pixels.m, horace_core/sqw/PixelData/@PixelData/recalc_pix_range.m
I've written an SMG for using the `PixelData` class. I've written some context on the problem it aims to address, as well as some principles behind the object. There are also a couple of examples on how to implement file-backed algorithms, and a few notes on things to be aware of.
Addresses #618 
_Note: I expect there will be some additions following our meeting tomorrow (24/03/21)_
=> Write SMG for using PixelData

tools/build_config/Jenkinsfile
Update the Jenkinsfile to be able to use the Jenkins shared library found: https://github.com/pace-neutrons/PACE-jenkins-shared-library thus allowing a cleaner and easier to maintain Jenkinsfile and consistency between the Jenkinsfiles of Herbert and Horace.
=> Use Jenkins shared library

documentation/add/04_mpi_framework.md
Attempt to clean up and clarify the a.d.d. as part of understanding what it is saying.
=> Clean up a.d.d. for mpi framework

cmake/PACE_Docs.cmake, documentation/user_docs/sphinx-build, tools/build_config/Jenkinsfile, tools/build_config/build.ps1
Issue due to conflict between new Jenkins shared lib and modifications made prior
=> Fix issue with Horace Jenkins breaking

cmake/PACE_Docs.cmake, tools/build_config/Jenkinsfile
Fix issue with pushing docs, and make CMake check for sphinx correctly.
=> Hotfix cleanup

horace_core/functions/spinw_disp.m
Changes the loop max to account for all the twins.
Addresses #660
=> Fix spinw interface twins loop

_test/test_algorithms/test_cut.m, documentation/adr/0023-error-format.md
Small addition to documentation, describing additional exception codes
=> Additional exception-s documentation

horace_core/spaghetti_plot.m
small change, fixing the issue #688
=> fixing issue with spagetti plot, producing non-orhtogonal projections

documentation/release_notes/v3.5.2.md
This is trivial PR, bringing release notes from bug-fix release 3.5.2 to master for the future
=> release_notes for bugfix

README.md
Merging to master the bugfixes identified on rel_3_6. All bugfixes are in Horace_gui, so testing is difficult but the user, seems happy
=> Fixing Horace GUI

documentation/smg/18_herbert_merger_proposal.md
Proposed plan to amalgamate Herbert and Horace repositories.
[View rendered markdown here](https://github.com/pace-neutrons/Horace/blob/822060afaa109a56bceb2a98fb77d978e5010a44/documentation/smg/18_herbert_merger_proposal.md).
=> Add herbert/horace amalgamation proposal SMG

_test/test_admin/test_paths.m, herbert_core/configuration/@herbert_config/private/process_unit_test_path.m, herbert_core/horace_paths.m
`horace_paths` did not get paths correctly if cleared.
=> Hotfix for paths

_test/test_utilities/test_projaxes_deprecation.m, documentation/user_docs/docs/user_guide/Interfacing_with_other_programs.rst, documentation/user_docs/docs/user_guide/Resolution_convolution.rst, horace_core/utilities/projaxes.m
added projaxes wrapper which refers to ortho_proj and generates deprecation warning
=> deprecated projaxes

_test/test_distribute/test_distribute.m, herbert_core/applications/multifit/@mfclass/mfclass.m, herbert_core/applications/multifit/@mfclass/private/is_valid_data.m, herbert_core/applications/multifit/@mfclass/private/multifit_lsqr_par.m, herbert_core/applications/multifit/@mfclass/private/strip_trailing_opts_.m, herbert_core/applications/multifit/@mfclass/set_data.m, herbert_core/utilities/classes/@IX_dataset/distribute.m, herbert_core/utilities/misc/distribute.m, horace_core/sqw/@DnDBase/DnDBase.m, horace_core/sqw/@DnDBase/distribute.m, horace_core/sqw/@sqw/distribute.m
Fix split, migrate to `distribute` attached to splittable objects, add splitting tests.
=> Fix split sqw

horace_core/sqw/@sqw/private/do_sqw_eval_average_filebacked_.m, horace_core/sqw/@sqw/private/do_sqw_eval_filebacked_.m, horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m, horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m, horace_core/sqw/PixelData/@PixelDataFileBacked/mask.m, horace_core/sqw/PixelData/@PixelDataMemory/PixelDataMemory.m
PR to branch to isolate changes for review
=> Add range generation in loops

_test/test_change_crystal/test_change_crystal_1.m, _test/test_change_crystal/test_change_crystal_1a.m, _test/test_change_crystal/test_change_crystal_bragg_coarse.m, _test/test_change_crystal/test_change_crystal_bragg_fine.m, _test/test_transformation/test_ortho_axes.m, _work/Alex_work/orient_crystal.m, herbert_core/utilities/maths/rotmat_to_rotvec2.m, horace_core/lattice_functions/refine_crystal.m
everything else was working there anyway
=> enabled all tests for crystal alignment

_test/shared/matlab_xunit/xunit/assertEqual.m, _test/test_algorithms/test_cut.m, _test/test_multifit/test_multifit_horace_1.m, _test/test_serializers/test_serializable_class.m, _test/test_sym_op/test_cut_sqw_sym.m, _test/test_transformation/test_ortho_proj_construction.m, herbert_core/utilities/classes/@serializable/private/eq_.m, herbert_core/utilities/classes/@serializable/private/process_inputs_for_eq_.m, herbert_core/utilities/classes/@serializable/serializable.m, horace_core/sqw/coord_transform/@ortho_proj/ortho_proj.m, horace_core/sqw/coord_transform/@ortho_proj/private/eq_.m
This is helper changes, defining ortho_proj comparison operator. 
The projections are considered equal if their transformation are equal.
=> ortho proj comparison

_test/test_sqw_class/common_sqw_class_state_holder.m, _test/test_sqw_class/test_equal_to_tol.m
Fix override of delete in `test_sqw_class/test_equal_to_tol` by calling superclass method
Fixes #1045
=> Fix overriden `delete` operation

_test/test_transformation/test_line_proj_construction.m, _test/test_utilities_herbert/test_subdiag_elements.m, herbert_core/utilities/maths/subdiag_elements.m, horace_core/lattice_functions/bragg_positions.m, horace_core/sqw/@Experiment/Experiment.m, horace_core/sqw/@sqw/lattice_parameters.m, horace_core/sqw/@sqw/private/set_from_old_struct_.m, horace_core/sqw/coord_transform/@aProjectionBase/aProjectionBase.m, horace_core/sqw/coord_transform/@ortho_proj/ortho_proj.m, horace_core/sqw/coord_transform/@ortho_proj/private/get_pix_img_transformation_.m, horace_core/sqw/coord_transform/@ortho_proj/private/init_by_input_parameters_.m, horace_core/sqw/coord_transform/@ortho_proj/private/transform_img_to_hkl_.m, horace_core/sqw/coord_transform/@spher_proj/private/find_ranges_.m, horace_core/sqw/file_io/@sqw_binfile_common/get_sqw.m, horace_core/sqw/file_io/@sqw_binfile_common/sqw_binfile_common.m
this should address #1005. The sample provided in the ticket works, despite its interface is outdate. 
The description modified according to the new reality
=> ortho proj constructor

_test/test_sqw_class/test_section.m, documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst, horace_core/sqw/@DnDBase/section.m, horace_core/sqw/@sqw/section.m
Fix section and add unit tests to verify
Fixes #800 
Fixes #511
=> Fix section and add unit tests

horace_core/configuration/@hor_config/hor_config.m, horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m
Move the file-backed scale factor to `hor_config`
Fixes #1108
=> Add file-backed scale factor to hor_config

_test/test_sqw_class/test_noisify.m, _test/test_sqw_file/test_faccess_sqw_v4.m
Fix wrong `scale_factor` in tests.
=> Hotfix `test_faccess_sqw_v4` and `test_noisify`

_test/test_serializers/test_serialize_symop.m, horace_core/symop/@Symop/Symop.m, horace_core/symop/@SymopGeneral/SymopGeneral.m, horace_core/symop/@SymopIdentity/SymopIdentity.m, horace_core/symop/@SymopReflection/SymopReflection.m, horace_core/symop/@SymopRotation/SymopRotation.m
- Make Symop serializable
- Add test to verify symop serializable
Fixes #1090
=> Make Symop serializable

horace_core/sqw/@sqw/calculate_qw_pixels.m
=> Fileback `calculate_qw_pixels`

documentation/smg/08_setting_up_jenkins_ci.md
Wanted to read this document but Notepad++ does not understand hml figures, so made it more consistent with markdown syntaxis. 
Trivial changes
=> Updated jenkins_ci SMG to work with Notepad++

horace_core/sqw/@sqw/coordinates_calc.m, horace_core/sqw/@sqw/func_eval.m, horace_core/sqw/@sqw/private/cut_accumulate_data_.m, horace_core/sqw/@sqw/private/do_sqw_eval_average_filebacked_.m, horace_core/sqw/@sqw/private/do_sqw_eval_filebacked_.m, horace_core/sqw/@sqw/section.m, horace_core/sqw/@sqw/shift_pixels.m, horace_core/sqw/@sqw/symmetrise_sqw.m, horace_core/sqw/@sqw/tobyfit_DGdisk_resconv.m, horace_core/sqw/@sqw/tobyfit_DGfermi_resconv.m, horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m, horace_core/sqw/PixelData/@PixelDataFileBacked/do_unary_op.m, horace_core/sqw/PixelData/@PixelDataFileBacked/mask.m, horace_core/sqw/PixelData/@PixelDataFileBacked/noisify.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_double_.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_pixels_.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_scalar_.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/binary_op_sigvar_.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/set_raw_data_.m, horace_core/sqw/PixelData/@PixelDataFileBacked/set_raw_fields.m, horace_core/utilities/sort_pix.m
Rename `PixelDataFileBacked.finalise` to `finish_dump` 
Fixes #1001
=> Rename `finalise` to `finish_dump`

_test/test_sqw_class/test_eval.m, horace_core/sqw/@sqw/private/do_sqw_eval_average_filebacked_.m, horace_core/sqw/@sqw/private/do_sqw_eval_filebacked_.m
Add tests, fix eval for file-backed objects
Fixes #1155
=> Fix use of outdated `pix.DEFAULT_PAGE_SIZE`

horace_core/GUI/horace.m
=> Fix erroneous name in Horace Unary Ops GUI

_test/test_sym_op/test_symop.m, horace_core/sqw/@DnDBase/define_target_axes_block.m, horace_core/symop/@Symop/Symop.m
Fix symmetric cuts by getting the appropriate binning in the symmetric projection space.
=> Fix symmetric cuts

documentation/user_docs/README.md
=> update urls for documentation in documentation

tools/mf_leg_to_new.py
=> Add converter for legacy multifit

_test/test_transformation/test_line_proj_transf_nonorth.m, horace_core/sqw/coord_transform/@line_proj/private/projtransf_to_img_.m
trivial bug and trivial fixture
=> projtransf bug

documentation/user_docs/README.md
In the README for the online documents, improve the wording and add in references to stable and unstabe
=> Further updates for the docs URL

documentation/user_docs/docs/manual/Unary_operations.rst, documentation/user_docs/docs/user_guide/Getting_started.rst
Since Unary ops is such a small update, included here.
=> Update getting started docs as well as unary ops

_test/test_sqw_pixels/test_mask.m, horace_core/sqw/@SQWDnDBase/sqw_eval.m, horace_core/sqw/@TmpFileHandler/TmpFileHandler.m, horace_core/sqw/@sqw/copy.m, horace_core/sqw/@sqw/get_new_handle.m, horace_core/sqw/@sqw/mask.m, horace_core/sqw/@sqw/mask_pixels.m, horace_core/sqw/@sqw/mask_random_fraction_pixels.m, horace_core/sqw/@sqw/mask_random_pixels.m, horace_core/sqw/@sqw/sqw.m, horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m, horace_core/sqw/PixelData/@PixelDataBase/private/parse_get_pix_args_.m, horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m, horace_core/sqw/PixelData/@PixelDataFileBacked/apply_c.m, horace_core/sqw/PixelData/@PixelDataFileBacked/private/init_.m, horace_core/sqw/PixelData/@PixelDataMemory/PixelDataMemory.m, horace_core/sqw/PixelData/@PixelDataMemory/apply_c.m, horace_core/sqw/page_operations/PageOpBase.m
Changes from review to ticket #1178
=> Minor changes from review to #1178. Mainly comments

_test/test_sqw_file/test_fcloser.m, herbert_core/utilities/misc/fcloser.m, horace_core/sqw/file_io/@binfile_v2_common/private/copy_contents_.m, horace_core/sqw/file_io/@faccess_sqw_v3/private/copy_contents_.m, horace_core/sqw/file_io/@faccess_sqw_v3_2/private/upgrade_file_format_.m, horace_core/sqw/file_io/@horace_binfile_interface/activate.m, horace_core/sqw/file_io/@horace_binfile_interface/deactivate.m, horace_core/sqw/file_io/@horace_binfile_interface/horace_binfile_interface.m, horace_core/sqw/file_io/@horace_binfile_interface/private/delete_.m, horace_core/sqw/file_io/@horace_binfile_interface/reopen_to_write.m, horace_core/sqw/file_io/@horace_binfile_interface/set_file_to_update.m
It is to simplify the file closer and test it. 
The closer should satisfy the following requests:
1) close file in case of failure, when run is interrupted by exception. 
2) Have a possibility to be called directly as default destructor is called at random moment of time and if we want e.g. to delete file, we want to close it first. 
This one seems satisfy this
Many improvements are possible
Depends on #1313/#1321 being merged
=> simple file closer

_test/test_IX_classes/test_IX_axis.m, _test/test_transformation/test_proj_captions.m, horace_core/sqw/axes_blocks/@sphere_axes/sphere_axes.m, horace_core/sqw/coord_transform/@sphere_proj/sphere_proj.m
=> Replace all instances of mEv with meV

documentation/user_docs/docs/Previous_versions.rst, documentation/user_docs/docs/Privacy_policy.rst, documentation/user_docs/docs/index.rst, documentation/user_docs/docs/manual/FAQ.rst
=> Update FAQ, add previous version page, remove privacy policy

documentation/add/10_single_filebacked_operations.md
ADD detailing decisions from meeting 11/1/23
=> Add ADD updating single-filebacked

horace_core/spaghetti_plot.m, horace_core/sqw/coord_transform/@aProjectionBase/aProjectionBase.m
- Add `transform_hkl_to_[pix|img]` routines to projection base for completeness
- Add `'withpix'` to return `sqw` with pixels rather than `dnd` (#1362)
- Modernise `spaghetti_plot` to use modern projection formats
- Fix issue with vector algebra using `max(abs(x))` rather than `vecnorm(x)`
- Fix issue with duplicate labels when matching `hkl` exist (comparison with curr_hkl(start) & prev_hkl(start) not end) (#808)
- Clean up and space out code
Still remaining issue of `ubmatrix` in `spaghetti_plot`
Fixes #808 
Fixes #1362
=> Spaghetti Plot Fixes

_test/test_config/test_config_classes.m, herbert_core/admin/@opt_config_manager/OptimalConfigInfo.xml, herbert_core/classes/MPIFramework/@ClusterDummy/ClusterDummy.m, herbert_core/classes/MPIFramework/@parallel_config/check_combo_arg.m, herbert_core/classes/MPIFramework/@parallel_config/parallel_config.m, herbert_core/classes/MPIFramework/@parallel_config/private/check_and_set_cluster_.m, herbert_core/classes/MPIFramework/@parallel_config/private/select_option_.m, herbert_core/configuration/@config_base/config_base.m
Fixes #1355 Two issues have been identified within the parallel config. I hope both have been fixed
=> parallel config issue

_LowLevelCode/cpp/serialiser/c_deserialize.cpp, _test/test_sqw_pixels/test_PixelData_binary_ops.m, herbert_core/utilities/classes/@IX_dataset/IX_dataset.m, herbert_core/utilities/classes/@data_op_interface/unary_op_manager.m
This is the PR to integrate changes and comments from review of PR #1370. It looks like no changes here yet, just comments.
=> Binary operation questions and comments from review

_test/test_mpi_wrappers/test_cluster_wrapper.m, herbert_core/classes/MPIFramework/@ClusterWrapper/ClusterWrapper.m
all tests are pasing manually on win and Linux but fail on Jenkins.
Attempt to identify the reason for failure
=> userpath -- looking for issues on Jenkins

horace_core/spaghetti_plot.m
- Add variable widths for q-segments to spaghetti plot
- Make noplot live up to its name (even in case of no action)
- Correct invalid_arguments to invalid_argument
Fixes #807
=> Add variable width spaghetti plot

horace_core/admin/cache.py
Existing utility updated to Python 3 and the Python avaliable on IDAAAAS
It is not much to test here, as it is not unit testable (or I do not know how to test it automatically)
It works on IDAAAS as expected -- I've just tested it. Unfortunately, does not help any more.
=> cache.py updated to python 3 and iDAAAS version of Python

tools/build_config/Jenkinsfile
- Make Jenkins support Python version variable
- Update defaults to match Rocky8 node modules
=> Migrate Jenkins CI to Rocky8

tools/build_config/Jenkinsfile
Pipelines demonstrating success:
https://anvil.softeng-support.ac.uk/jenkins/job/PACE-neutrons/job/Horace/job/Test-Rocky8-2021a/1/
https://anvil.softeng-support.ac.uk/jenkins/job/PACE-neutrons/job/Horace/job/Test-VM-Win-10-2021a/3/
=> Fix CI by removing R when loading matlab module only

_test/test_transformation/test_aProjection_methods.m, horace_core/sqw/coord_transform/@aProjectionBase/aProjectionBase.m
additional fixture to #1533; for which PR#1541 let small bug(typo in `transform_img_to_hkl`) in. 
The fixture and unit test ensuring its run
=> bose spherproj fixture

_test/test_sqw_pageOpMethods/test_binary_ops.m, documentation/user_docs/docs/manual/Binary_operations.rst
fixes #1525
The test shows that sqw - dnd operates correctly
=> Check for `sqw-dnd` and user documentaion explaining it

_test/test_sqw/test_save.m, horace_core/sqw/@SQWDnDBase/save.m
refactored code and added bunch of unit tests which show that issue #1524 is fixed
=> saving array of files

tools/build_config/Jenkinsfile
Should solve problem on Rocky8 with old Jenkinsfile
=> Fix rel3.6 jenkins

_test/test_experiment/test_experiment_cnstrct_and_properties.m, herbert_core/utilities/classes/@unique_objects_container/unique_objects_container.m, herbert_core/utilities/classes/@unique_references_container/unique_references_container.m, horace_core/sqw/@Experiment/Experiment.m, horace_core/sqw/@Experiment/private/init_.m
(1) Further use of existing hashes to prevent further hash calculations
(2) Remove duplicate calculations of Experiment contents
=> Removing unneeded hashes from the container population stages of Horace

_test/common_functions/@SQW_GENCUT_perf_tester/SQW_GENCUT_perf_tester.m, _test/common_functions/@SQW_GENCUT_perf_tester/combine_task_performance.m, _test/common_functions/@SQW_GENCUT_perf_tester/gen_sqw_task_performance.m, _test/common_functions/@SQW_GENCUT_perf_tester/private/generate_source_test_files_.m, _test/performance_test/run_performance_tests.m, _test/performance_test/test_SQW_GENCUT_perf.m
while searching for possible bug in write_nsqw_to_sqw I have modified perfromance tests to be more flexible. 
These changes may be useful in a future so woth to committ them to master.
=> changes to run performance

_test/test_sym_op/test_cut_sqw_sym.m, horace_core/sqw/@sqw/cut.m, horace_core/sqw/@sqw/private/cut_accumulate_data_.m, horace_core/sqw/@sqw/private/cut_single_.m, horace_core/symop/@Symop/Symop.m
=> Fix issue with cut_sym not transforming pixels

horace_core/admin/cache.py
- Convert to modern Python (min 3.6; f-strings) 
- Add type hints
Re #1460
=> Pythonise cache.py

herbert_core/utilities/classes/@IX_dataset/distribute.m
=> Remove combo-arg checking while distributing IX_dataset objects

tools/mf_leg_to_new.py
Replace regex argument extraction with rudimentary bracket-matching algorithm to catch multiply nested arguments correctly
Fixes #1505
=> Add parser for bracket-matching

documentation/user_docs/docs/manual/Parallel.rst
=> Update Parallel docs to warn of memory usage

documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst, documentation/user_docs/docs/manual/Input_file_formats.rst, documentation/user_docs/docs/manual/Reshaping_etc.rst
c.f. #1513 for upload of review
=> Add changes requested in Travis' review

tools/mf_leg_to_new.py
Fixes issue where having `list` or certain values in converted arguments led to invalidation of format lines due to bare `replace`. With new bracket-finding algorithm there's no need for this `replace` at all.
=> Fix issues with mf_leg_to_new and add tests

_test/test_utilities/test_warnonce.m, herbert_core/utilities/general/warnonce.m
Related to #1609 
Does not use this function anywhere, but provides function for later PRs
=> Add `warnonce` function to trigger a warning only once

README.md
Make links to documentation more obvious at first glance.
Fixes #1664
=> Update front-page for clarity

herbert_core/classes/data_loaders/@rundata/private/gen_runfiles_.m
fixes Re #1663. Small addition makes working with gen_sqw so much nicer
=> gen sqw progress

documentation/user_docs/docs/User_guide.rst, documentation/user_docs/docs/user_guide/Horace3_to_4.rst
=> Add doc describing how to convert Horace 3 -> 4

_test/test_utilities/test_projaxes_deprecation.m, documentation/user_docs/docs/user_guide/Horace3_to_4.rst, herbert_core/configuration/herbert_config.m, horace_core/algorithms/write_spe_to_sqw.m, horace_core/fake_data.m, horace_core/horace_cut_nan_inf.m, horace_core/horace_info_level.m, horace_core/sqw/@sqw/symmetrise_sqw.m, horace_core/symop/@Symop/Symop.m, horace_core/utilities/@MagneticIons/fix_magnetic_ff.m, horace_core/utilities/depecating/axes_block.m, horace_core/utilities/depecating/ortho_axes.m, horace_core/utilities/depecating/ortho_proj.m, horace_core/utilities/depecating/projaxes.m, horace_core/utilities/depecating/spher_axes.m, horace_core/utilities/depecating/spher_proj.m
Believed to be a complete set of deprecation changes
Fixes #1643
=> Standardise deprecations

documentation/user_docs/docs/manual/Correcting_for_sample_misalignment.rst, documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst, horace_core/lattice_functions/bragg_positions.m
Fixes Re #1687. Here is the documentation for crystal alignment. 
As some inconsistency in description was found, it changes both documentation and description of the code, code tests are running at least once, and then I will put documentation tag to it.
=> alignment documentation

documentation/user_docs/docs/manual/Planning_a_Horace_scan.rst, documentation/user_docs/docs/manual/Symmetrising_etc.rst
- Migrate section on `Symop` to end and mark as advanced
- Suggest DGS planner 
- Rewrite parallel path issue
- Restate `symmetrise_sqw` restrictions
=> Respond to David's comments on documentation except ResConv

documentation/user_docs/docs/manual/Correcting_for_sample_misalignment.rst
These are changes arranges according to Travis feedback.
=> Alignment feedback

documentation/release_notes/v4.0.2.md
Addresses Re #1831
short description of things which come to Release 4.0.2
=> Description of Release 4.0.2

documentation/add/12_Horace_graphics.md, documentation/release_notes/v4.0.3.md
solves Re #1859.
In addition to that, contains short description of changes introduced in ticket  Re #1787 (release notes) and minor bug fix for table formatting
=> Add for horace graphics
